#!/usr/bin/env python3
"""Synthetic Forex ledger/planning command contracts; local Node VM, no network."""
import argparse,hashlib,json,shutil,subprocess
from pathlib import Path
PATHS=['src/js/30-accounting/01-daily-ledger.js','src/js/30-accounting/05-fx-planning/01-fx-model.js','src/js/30-accounting/05-fx-planning/02-fx-engine.js','src/js/30-accounting/05-fx-planning/03-fx-state.js']
NODE=r'''
const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const input=JSON.parse(fs.readFileSync(0,'utf8'));let unknown=false,writes=0,mode='true',disk=null;
const c={window:{},Date,Math,JSON,structuredClone,crypto:crypto.webcrypto,clearTimeout,setTimeout,
 hideStaleSavedTag(){},persistenceAlertEl(){return null;},layoutPersistenceBanners(){},
 jpWealthPersistenceOutcomeIsUnknown(){return unknown;},markJPWealthPersistenceOutcomeUnknown(){unknown=true;},
 save(){writes++;if(mode==='false')return false;if(mode==='throw')throw Error('synthetic');disk=JSON.stringify(c.S);return mode==='undefined'?undefined:true;},
 dgLogChange(...a){c.S.dataGovernance.changeLog.push(a);},reserveRequirementsCalc(){return {};}};
c.window.JPWForex={policy:{planning:{referenceMonthlyReturn:.035,annualReferenceRange:[.35,.40]}},state:{recordContext(){return {accountId:'account-A',periodId:'period-A',policyVersion:'fixture-v11'};}}};
vm.createContext(c);for(const p of input.paths)vm.runInContext(input.sources[p],c,{filename:p});
const run=s=>vm.runInContext(s,c),clone=x=>JSON.parse(JSON.stringify(x));
const eq=(a,b)=>assert.deepStrictEqual(clone(a),clone(b)),near=(a,b)=>assert(Math.abs(a-b)<1e-8,`${a} != ${b}`);
function seed(){unknown=false;mode='true';writes=0;c.S={params:{saldoIni:1000,saldoAtu:1000,inicio:'2026-01-01'},ledger:[],ledgerHistory:{schemaVersion:1,events:[]},dataGovernance:{changeLog:[]},fxPlanning:{schemaVersion:1,plan:null,auditLog:[]}};}
const plan=()=>assert(run(`fxPlanCreate({name:'Synthetic',assumptions:{startMonth:'2026-01',horizonMonths:4,initialBalanceUsd:1000,defaultMonthlyReturn:.01}})`).ok);
const record=()=>run(`ledgerRecord({data:'2026-01-02',resultado:10,saldo:1010})`);
const actual=()=>assert(run(`fxPlanRecordActual('2026-01',{inputType:'usd',profitUsd:10})`).ok);
const series=()=>run('fxForecastTimeline(fxActivePlan())');
const tests=[];function test(name,fn){seed();fn();tests.push({name,status:'PASS'});}
test('baseline arithmetic',()=>{const r=run(`fxPlannedTimeline({startMonth:'2026-01',horizonMonths:4,initialBalanceUsd:1000,defaultMonthlyReturn:.01,monthOverrides:{'2026-03':-.02},plannedContributions:{'2026-01':{personalUsd:100,propUsd:0}}})`);[1110,1121.1,1098.678,1109.66478].forEach((v,i)=>near(r[i].close,v));});
test('legacy read is non-mutating',()=>{c.S.ledger=[{data:'2026-01-01',resultado:0,saldo:1000,extension:7}];const b=clone(c.S);assert.equal(run('ledgerRows()[0].provenance'),'LEGACY_UNRESOLVED');eq(c.S,b);assert.equal(writes,0);});
test('zero, correction versions and before-after history',()=>{let r=run(`ledgerRecord({data:'2026-01-02',resultado:0,saldo:''})`);assert(r.ok);assert.equal(r.row.accountId,'account-A');r=c.window.JPWLedger.correct(r.row.id,{data:r.row.data,resultado:10,saldo:1010},{reason:'broker correction',expectedVersion:1});assert(r.ok);assert.equal(r.row.version,2);assert.equal(c.S.ledgerHistory.events[1].before.resultado,0);assert.equal(c.S.ledgerHistory.events[1].after.resultado,10);});
test('stale correction and missing reason',()=>{const r=record(),b=clone(c.S),n=writes;assert(!c.window.JPWLedger.correct(r.row.id,{data:r.row.data,resultado:99,saldo:1099},{reason:'stale',expectedVersion:0}).ok);assert(!c.window.JPWLedger.correct(r.row.id,{data:r.row.data,resultado:99,saldo:1099},{expectedVersion:1}).ok);eq(c.S,b);assert.equal(writes,n);});
test('invalid date and absent result are not zero',()=>{for(const v of [null,'',' ',undefined,Infinity,NaN,true,false,[],{}])assert(!c.window.JPWLedger.record({data:'2026-01-02',resultado:v,saldo:1000}).ok);assert(!c.window.JPWLedger.record({data:'2026-02-30',resultado:0,saldo:1000}).ok);assert.equal(writes,0);});
test('void retains original audit',()=>{const r=record();assert(c.window.JPWLedger.void(r.row.id,{reason:'duplicate',expectedVersion:1}).ok);assert.equal(c.S.ledger.length,0);assert.equal(c.S.ledgerHistory.events[1].before.resultado,10);});
test('ledger false rolls back all scoped state',()=>{const b=clone(c.S);mode='false';assert(!record().ok);eq(c.S,b);});
test('ledger unknown preserves attempt and blocks repeat',()=>{mode='throw';assert.equal(record().persistido,null);assert.equal(c.S.ledger.length,1);const n=writes;assert(!run(`ledgerRecord({data:'2026-01-03',resultado:0,saldo:1010})`).ok);assert.equal(writes,n);});
test('unknown history schema preserved',()=>{c.S.ledgerHistory={schemaVersion:9,opaque:'preserve'};const b=clone(c.S);assert(!record().ok);eq(c.S,b);assert.equal(writes,0);});
test('row N changes suffix and preserves prefix/actual/baseline',()=>{plan();actual();const b=series(),base=clone(c.S.fxPlanning.plan.baseline),a=clone(c.S.fxPlanning.plan.actuals);assert(run(`fxPlanReviseFromMonth('2026-03',{rate:.02,personalUsd:100,propUsd:0},'March')`).ok);const r=series();eq(r.slice(0,2),b.slice(0,2));near(r[2].close,b[2].open*1.02+100);near(r[3].open,r[2].close);eq(c.S.fxPlanning.plan.baseline,base);eq(c.S.fxPlanning.plan.actuals,a);assert(!run(`fxPlanReviseFromMonth('2026-01',{rate:.9},'closed')`).ok);});
test('new revision reconstructs exact source after actual edit',()=>{plan();actual();const b=series();run(`fxPlanReviseFromMonth('2026-03',{rate:.02},'revision')`);run(`fxPlanRecordActual('2026-01',{inputType:'usd',profitUsd:20})`);eq(run('fxForecastAtRevision(fxActivePlan(),0)'),b);assert.equal(c.S.fxPlanning.plan.actualHistory[1].before.profitUsd,10);});
test('explicit rebase preserves prefix and facts',()=>{plan();actual();const b=series(),base=clone(c.S.fxPlanning.plan.baseline),a=clone(c.S.fxPlanning.plan.actuals);assert(run(`fxPlanRebase('2026-03',2000,'future anchor')`).ok);const r=series();eq(r.slice(0,2),b.slice(0,2));near(r[2].open,2000);near(r[3].open,2020);eq(c.S.fxPlanning.plan.baseline,base);eq(c.S.fxPlanning.plan.actuals,a);assert(!run(`fxPlanRebase('2026-01',2000,'closed')`).ok);});
test('scenario leaves PLAN and ACTUAL unchanged',()=>{plan();actual();const b=series(),a=clone(c.S.fxPlanning.plan.actuals),cur=clone(c.S.fxPlanning.plan.current),r=run(`fxScenarioSave({name:'Cautious'})`);assert(r.ok);assert(c.window.JPWFx.state.fxPlanReviseFromMonth('2026-02',{rate:0},'flat',r.id).ok);const sc=c.S.fxPlanning.plan.scenarios[0],rows=c.window.JPWFx.engine.fxScenarioTimeline(run('fxActivePlan()'),sc);eq(rows[0],b[0]);near(rows[1].close,1010);eq(c.S.fxPlanning.plan.current,cur);eq(c.S.fxPlanning.plan.actuals,a);assert(c.window.JPWFx.state.fxScenarioDelete(r.id).ok);assert.equal(c.S.fxPlanning.plan.scenarioArchive.length,1);});
test('planning refusal rollback and UNKNOWN',()=>{plan();const b=clone(c.S);mode='false';assert(!run(`fxPlanRebase('2026-02',2000,'test')`).ok);eq(c.S,b);mode='throw';assert.equal(run(`fxPlanRebase('2026-02',2000,'test')`).persistido,null);const n=writes;assert(!run(`fxPlanRebase('2026-02',2000,'test')`).ok);assert.equal(writes,n);});
test('actual absence rejected, explicit zero accepted',()=>{plan();assert(!run(`fxPlanRecordActual('2026-01',{inputType:'usd',profitUsd:null})`).ok);assert(!run(`fxPlanRecordActual('2026-01',{inputType:'rate',returnRate:''})`).ok);assert(run(`fxPlanRecordActual('2026-01',{inputType:'usd',profitUsd:0})`).ok);});
test('coercible objects and whitespace are not financial inputs',()=>{plan();const b=clone(c.S),n=writes;for(const v of [true,false,[],{},' ']){assert(!c.window.JPWFx.state.fxPlanRecordActual('2026-01',{inputType:'usd',profitUsd:v}).ok);assert(!c.window.JPWFx.state.fxPlanReviseFromMonth('2026-02',{rate:v},'invalid').ok);}eq(c.S,b);assert.equal(writes,n);});
test('numeric legacy strings calculate in copy without concatenation',()=>{c.S.ledger=[{data:'2026-01-02',resultado:'10',saldo:'1010',referenceBalance:'1000',accountId:'account-A',periodId:'period-A'}];const b=clone(c.S),r=run(`ledgerMonthlyActual('2026-01',{accountId:'account-A',periodId:'period-A',complete:true})`);assert.equal(r.status,'COMPLETE');assert.equal(r.profitUsd,10);eq(c.S,b);assert.equal(writes,0);});
test('monthly provenance and completeness explicit',()=>{record();assert.equal(run(`ledgerMonthlyActual('2026-01',{})`).status,'PARTIAL');assert.equal(run(`ledgerMonthlyActual('2026-01',{accountId:'account-A',periodId:'period-A',complete:false})`).status,'PARTIAL');assert.equal(run(`ledgerMonthlyActual('2026-01',{accountId:'account-A',periodId:'period-A',complete:true})`).status,'COMPLETE');});
test('import retains source, rejects overwrite/stale, explicit replace',()=>{plan();const rec=record(),ctx={accountId:'account-A',periodId:'period-A',complete:true};let p=c.window.JPWLedger.monthlyActual('2026-01',ctx);assert(c.window.JPWFx.state.fxPlanImportLedgerActual('2026-01',{...ctx,sourceVersion:p.source.version}).ok);eq(c.S.fxPlanning.plan.actuals['2026-01'].source,p.source);assert(!c.window.JPWFx.state.fxPlanImportLedgerActual('2026-01',{...ctx,sourceVersion:p.source.version}).ok);assert(c.window.JPWLedger.correct(rec.row.id,{data:'2026-01-02',resultado:15,saldo:1015},{reason:'corrected source',expectedVersion:1}).ok);assert(!c.window.JPWFx.state.fxPlanImportLedgerActual('2026-01',{...ctx,sourceVersion:p.source.version,replace:true}).ok);assert.equal(c.S.fxPlanning.plan.actuals['2026-01'].profitUsd,10);p=c.window.JPWLedger.monthlyActual('2026-01',ctx);assert(c.window.JPWFx.state.fxPlanImportLedgerActual('2026-01',{...ctx,sourceVersion:p.source.version,replace:true}).ok);assert.equal(c.S.fxPlanning.plan.actuals['2026-01'].profitUsd,15);});
test('inconsistent daily chain blocks import',()=>{plan();run(`ledgerRecord({data:'2026-01-02',resultado:10,saldo:1020})`);const ctx={accountId:'account-A',periodId:'period-A',complete:true},p=c.window.JPWLedger.monthlyActual('2026-01',ctx);assert.equal(p.status,'PARTIAL');assert(!c.window.JPWFx.state.fxPlanImportLedgerActual('2026-01',{...ctx,sourceVersion:p.source.version}).ok);});
test('roundtrip preserves history and opaque extensions',()=>{plan();c.S.fxPlanning.plan.extension={opaque:[1,2]};record();actual();run(`fxScenarioSave({name:'Saved'})`);run(`fxPlanRebase('2026-02',2000,'explicit')`);const b=clone(c.S);c.S=JSON.parse(disk);eq(c.S,b);eq(run('fxActivePlan().extension'),{opaque:[1,2]});assert.equal(c.S.ledgerHistory.events.length,1);assert.equal(c.S.fxPlanning.plan.actualHistory.length,1);});
test('future FX envelope refuses without normalization',()=>{c.S.fxPlanning={schemaVersion:9,opaque:'preserve'};const b=clone(c.S);assert(!run(`fxScenarioSave({name:'blocked'})`).ok);eq(c.S,b);assert.equal(writes,0);});
test('observed balance can be recorded without risk reference',()=>{c.S.params.saldoIni=null;assert(c.window.JPWLedger.record({data:'2026-01-02',resultado:10,saldo:1010}).ok);assert.equal(c.S.ledger[0].referenceBalance,null);});
test('explicit legacy origin correction enables provenance',()=>{c.S.ledger=[{data:'2026-01-02',resultado:10,saldo:1010,referenceBalance:1000}];const id=run('ledgerRows()[0].id');assert(c.window.JPWLedger.correct(id,{data:'2026-01-02',resultado:10,saldo:1010},{reason:'identified source',expectedVersion:0,reconcileContext:true,context:{accountId:'account-A',periodId:'period-A'}}).ok);assert.equal(c.S.ledger[0].accountId,'account-A');assert.equal(c.S.ledgerHistory.events[0].before.accountId,undefined);});
test('empty monthly source is unavailable, not zero profit',()=>{const r=run(`ledgerMonthlyActual('2026-01',{accountId:'account-A',periodId:'period-A',complete:true})`);assert.equal(r.status,'PARTIAL');assert.equal(r.profitUsd,null);});
test('read projections and references never save',()=>{plan();const n=writes,b=JSON.stringify(c.S);run('fxActivePlan();fxOverviewLive();fxForecastTimeline(fxActivePlan());fxPlanningReferences();');assert.equal(writes,n);assert.equal(JSON.stringify(c.S),b);eq(run('fxPlanningReferences()'),{monthly:.035,annualRange:[.35,.4]});});
console.log(JSON.stringify({status:'PASS',tests},null,2));
'''
def main():
    p=argparse.ArgumentParser();p.add_argument('--root',type=Path,default=Path(__file__).resolve().parents[1]);p.add_argument('--artifacts',type=Path);p.add_argument('--node',default=shutil.which('node') or str(Path.home()/'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/bin/node'));a=p.parse_args()
    sources={p:(a.root/p).read_text() for p in PATHS}
    r=subprocess.run([a.node,'-e',NODE],input=json.dumps({'paths':PATHS,'sources':sources}),text=True,capture_output=True)
    if r.returncode:print(r.stdout);print(r.stderr);raise SystemExit(r.returncode)
    report=json.loads(r.stdout);report['sources']={p:hashlib.sha256(s.encode()).hexdigest() for p,s in sources.items()}
    if a.artifacts:a.artifacts.mkdir(parents=True,exist_ok=True);(a.artifacts/'ledger-planning-domain.json').write_text(json.dumps(report,indent=2))
    print(f"PASS {len(report['tests'])}/{len(report['tests'])} ledger/planning command contracts")
if __name__=='__main__':main()
