#!/usr/bin/env python3
"""Original V11 reader: isolated real product/browser, synthetic financial state.

The only non-synthetic document read is the public canonical normative PDF.
No owner browser profile, account/export, dependency installation or gate edits.
"""
from __future__ import annotations
import argparse
import base64
import hashlib
import json
from pathlib import Path
import re
import sys
import tempfile

sys.dont_write_bytecode = True
from playwright.sync_api import sync_playwright
from dashboard_macro_test import boot as dashboard_boot, launch_browser, serve
from browser_bootstrap_fixture import install_bootstrap, wait_bootstrap, assert_fixture_requests
from statute_documentary_test import SEED, SNAPSHOT

ROOT = Path(__file__).resolve().parents[1]
ADAPTER = 'src/js/20-ui/34-normative-reader.js'
PDF = 'docs/normative/Estatuto_JP_WEALTH_UNIFICADO.pdf'
PAYLOAD = 'src/vendor/normative/statute-payload.js'
SHA = '2dab6166bb8513cd9beb7fe39c574971af086ebae66683d99c0e6fac69eb6769'
TRACKING = """window.__normativeWorkers=[];window.__normativeURLs=[];window.__normativeRevoked=[];
const NRWorker=Worker;window.Worker=class extends NRWorker{constructor(url,options){super(url,options);this.nrRow={name:options?.name||'',terminated:false};__normativeWorkers.push(this.nrRow)}terminate(){this.nrRow.terminated=true;super.terminate()}};
const NRCreate=URL.createObjectURL.bind(URL),NRRevoke=URL.revokeObjectURL.bind(URL);
URL.createObjectURL=b=>{const u=NRCreate(b);__normativeURLs.push(u);return u};URL.revokeObjectURL=u=>{__normativeRevoked.push(u);return NRRevoke(u)};"""


def digest(data):
    return hashlib.sha256(data).hexdigest()


def prepare(context):
    install_bootstrap(context)
    context.add_init_script(TRACKING)
    context._nr_console_errors = []
    context.on('console', lambda msg: context._nr_console_errors.append({'text': msg.text, 'location': msg.location}) if msg.type == 'error' else None)


def boot(browser, url, viewport=None, accepted=True, service_workers='allow'):
    context, page, observed = dashboard_boot(browser, url, viewport=viewport, prepare_context=prepare, service_workers=service_workers)
    wait_bootstrap(page)
    page.evaluate(SEED, {'version': 'V11.0+JPW-ANNEX-T03', 'accepted': accepted})
    page.evaluate("closeModal();if(typeof closeSettings==='function')closeSettings();")
    return context, page, observed


def navigate(page):
    assert page.evaluate("JPWNavigation.navigate('tools-normative')"), 'Normative route rejected'
    page.wait_for_function("!jpwNormativePage.hidden && !jpwNormativePage.inert")


def ready(page, number=None):
    try:
        page.wait_for_function("() => JPWNormativeReader.snapshot().verified && JPWNormativeReader.snapshot().renderedPage!==null && jpwNormativePage.getAttribute('aria-busy')==='false'", timeout=45000)
        if number is not None:
            page.wait_for_function("n => JPWNormativeReader.snapshot().renderedPage===n && jpwNormativePage.getAttribute('aria-busy')==='false'", arg=number, timeout=45000)
    except Exception:
        print(json.dumps(page.evaluate("({snapshot:JPWNormativeReader.snapshot(),status:nrStatus.textContent,integrity:nrIntegrity.textContent,busy:jpwNormativePage.getAttribute('aria-busy'),hidden:jpwNormativePage.hidden})"),ensure_ascii=False),flush=True)
        raise


def go(page, number):
    page.locator('#nrPage').fill(str(number))
    page.locator('#nrPage').press('Enter')
    ready(page, number)


def pixels(page):
    return page.evaluate("""() => {const c=nrPageHost.querySelector('canvas');if(!c)return null;const data=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let ink=0;for(let i=0;i<data.length;i+=388)if(data[i]<240||data[i+1]<240||data[i+2]<240)ink++;const spans=[...nrPageHost.querySelectorAll('.textLayer span:not(.markedContent)')];return {width:c.width,height:c.height,ink,spans:spans.length,font:spans.length?parseFloat(getComputedStyle(spans[0]).fontSize):0}}""")


def unchanged(page, before):
    after = page.evaluate(SNAPSHOT)
    for field in ('state', 'storage', 'onboarding', 'history', 'finance'):
        assert after[field] == before[field], ('reader changed protected synthetic state', field)
    assert after['writes'] == before['writes'], 'reader wrote financial/local storage'


def source_checks():
    original = (ROOT / PDF).read_bytes()
    assert len(original) == 1499074 and digest(original) == SHA
    payload = json.loads((ROOT / PAYLOAD).read_text().split('window.JPW_NORMATIVE_STATUTE = ', 1)[1].rstrip(';\n'))
    assert payload['id'] == 'estatuto-v11' and payload['version'] == 'V11.0'
    assert payload['path'] == PDF and payload['bytes'] == len(original) and payload['sha256'] == SHA
    assert base64.b64decode(payload['base64']) == original, 'generated bytes differ from original'
    portable = (ROOT / 'dist/JP_Wealth_Risk_Terminal_V9.1_PORTABLE.html').read_text()
    embedded = re.search(r'window\.JPW_NORMATIVE_STATUTE = (\{[^\n]+\});\n', portable)
    assert embedded and json.loads(embedded.group(1)) == payload, 'portable payload differs'
    source = (ROOT / ADAPTER).read_text()
    assert not re.search(r'https?://|localStorage|sessionStorage|\bsave\(|\bS\.', source), 'unexpected external/storage access in reader'
    assert 'isEvalSupported:false' in source and 'enableXfa:false' in source
    return original


def exercise(page, context, original, mode, screenshots):
    navigate(page);ready(page, 1)
    before = page.evaluate(SNAPSHOT)
    actual = pixels(page)
    assert actual and actual['ink'] > 50 and actual['spans'] > 1 and actual['font'] > 0, (mode, actual)
    assert page.locator('#nrIntegrity').get_attribute('data-state') == 'verified'
    page.locator('#nrNext').click();ready(page, 2)
    assert pixels(page)['ink'] > 50
    page.locator('#nrPrev').click();ready(page, 1)
    page.locator('#nrPage').fill('126');page.locator('#nrPage').press('Enter')
    assert page.locator('#nrPage').input_value() == '1' and 'entre 1 e 125' in page.locator('#nrStatus').inner_text()
    for number in (86, 91, 110):
        go(page, number)
        assert pixels(page)['ink'] > 50 and pixels(page)['spans'] > 5, (mode, number, pixels(page))
        if screenshots and mode == 'http':page.locator('#nrViewport').screenshot(path=str(screenshots / ('page-' + str(number) + '.png')))
    go(page, 125)
    assert page.locator('#nrNext').is_disabled() and pixels(page)['ink'] > 20
    go(page, 2)
    old = page.locator('#nrZoomLabel').inner_text();page.locator('#nrZoomIn').click()
    page.wait_for_function("old => nrZoomLabel.textContent!==old && jpwNormativePage.getAttribute('aria-busy')==='false'", arg=old)
    page.locator('#nrRotate').click()
    page.wait_for_function("JPWNormativeReader.snapshot().rotation===90 && jpwNormativePage.getAttribute('aria-busy')==='false'")
    size = page.evaluate("({w:parseFloat(nrPageHost.querySelector('canvas').style.width),h:parseFloat(nrPageHost.querySelector('canvas').style.height)})")
    assert size['w'] > size['h'], size
    page.locator('#nrFit').click();ready(page, 2)
    # Restore upright and test search across all 125 pages without OCR.
    for _ in range(3):
        page.locator('#nrRotate').click()
        page.wait_for_function("jpwNormativePage.getAttribute('aria-busy')==='false'")
    page.locator('#nrSearch').fill('capital');page.locator('#nrFind').click()
    page.wait_for_function("nrSearchStatus.textContent.startsWith('Resultado ')", timeout=45000)
    assert page.evaluate('JPWNormativeReader.snapshot().matches') > 1
    ready(page)
    page.locator('#nrSearchNext').click()
    assert 'Resultado 2 de' in page.locator('#nrSearchStatus').inner_text()
    ready(page)
    assert page.locator('.nr-found').count() > 0
    page.locator('#nrSearch').fill('gestão');page.locator('#nrFind').click()
    page.wait_for_function("nrSearchStatus.textContent.startsWith('Resultado ')")
    accented = page.evaluate('JPWNormativeReader.snapshot().matches')
    assert accented > 0
    ready(page)
    page.locator('#nrSearch').fill('GESTAO');page.locator('#nrFind').click()
    page.wait_for_function("nrSearchStatus.textContent.startsWith('Resultado ')")
    assert page.evaluate('JPWNormativeReader.snapshot().matches') == accented
    ready(page)
    page.locator('#nrSearch').fill('ZZZ_NORMATIVE_NO_MATCH_349151');page.locator('#nrFind').click()
    page.wait_for_function("nrSearchStatus.textContent.startsWith('Nenhum resultado')")
    assert page.evaluate('JPWNormativeReader.snapshot().matches') == 0
    go(page, 2)
    page.locator('#nrThumbToggle').click()
    page.wait_for_function("nrThumbList.querySelector('button canvas')!==null", timeout=45000)
    page.locator('#nrThumbList button[data-page="3"]').click();ready(page, 3)
    page.locator('#nrThumbToggle').click();ready(page, 3)
    # Real TextLayer selection, with the native clipboard where permissions exist.
    selected = page.evaluate("""() => {const spans=[...nrPageHost.querySelectorAll('.textLayer span:not(.markedContent)')].filter(s=>s.textContent.trim());const range=document.createRange();range.selectNodeContents(spans[0]);const s=getSelection();s.removeAllRanges();s.addRange(range);return s.toString()}""")
    assert selected.strip()
    if mode in ('http', 'offline'):
        context.grant_permissions(['clipboard-read', 'clipboard-write'])
        page.locator('#nrCopy').click()
        page.wait_for_function("nrStatus.textContent.includes('copiado')")
        assert page.evaluate('navigator.clipboard.readText()') == selected
    else:
        page.locator('#nrCopy').click()
        page.wait_for_function("nrStatus.textContent.includes('copiado') || nrStatus.textContent.includes('selecionado')")
    with page.expect_download() as pending:
        page.locator('#nrDownload').click()
    download = pending.value
    assert digest(Path(download.path()).read_bytes()) == SHA and download.suggested_filename == 'Estatuto_JP_Wealth_V11.pdf'
    assert page.locator('#nrOriginal').get_attribute('href').startswith('blob:')
    assert page.locator('#nrOriginal').get_attribute('target') == '_blank'
    assert 'noopener' in page.locator('#nrOriginal').get_attribute('rel')
    assert page.locator('#nrOriginal').get_attribute('download') is None
    with context.expect_page() as opened:
        page.locator('#nrOriginal').click()
    popup = opened.value
    # Chromium headless cannot navigate/render its native PDF viewer. The
    # real popup event proves activation; bytes/target are checked separately.
    # https://playwright.dev/python/docs/api/class-page#page-goto
    assert popup in context.pages
    popup.close()
    page.locator('#nrFullscreen').click();page.wait_for_function("jpwNormativePage.classList.contains('nr-expanded')")
    page.keyboard.press('Escape');page.wait_for_function("!jpwNormativePage.classList.contains('nr-expanded')")
    go(page, 2)
    page.locator('#nrViewport').focus();page.keyboard.press('PageDown');ready(page, 3)
    page.keyboard.press('Home');ready(page, 1)
    unchanged(page, before)
    if screenshots:
        page.locator('#jpwNormativePage').screenshot(path=str(screenshots / (mode + '-desktop.png')))
    # The reader must be fully disposed by accepted navigation out of Tools.
    assert page.evaluate("JPWNavigation.navigate('dashboard')")
    page.wait_for_function("!JPWNormativeReader.snapshot().active")
    resources = page.evaluate("({workers:__normativeWorkers.filter(w=>w.name==='JPW Estatuto V11 local'),urls:__normativeURLs,revoked:__normativeRevoked})")
    assert resources['workers'] and all(row['terminated'] for row in resources['workers']), resources
    assert set(resources['urls']) <= set(resources['revoked']), resources
    navigate(page);ready(page, 1)
    page.evaluate('JPWNormativeReader.leave();JPWNormativeReader.enter();JPWNormativeReader.leave();')
    page.wait_for_function('!JPWNormativeReader.snapshot().active')
    page.evaluate('JPWNormativeReader.enter()');ready(page, 1)
    unchanged(page, before)


def main():
    parser = argparse.ArgumentParser();parser.add_argument('--out');parser.add_argument('--screenshots');parser.add_argument('--modes', default='http,modular-file,portable-file,offline');args = parser.parse_args()
    modes=args.modes.split(',')
    assert modes and set(modes)<= {'http','modular-file','portable-file','offline'}, modes
    output = Path(args.out) if args.out else None
    screenshots = Path(args.screenshots) if args.screenshots else None
    if screenshots:screenshots.mkdir(parents=True, exist_ok=True)
    checked = [ADAPTER, PDF, PAYLOAD, 'tools/rebuild_monolith.py']
    source_hashes = {path: digest((ROOT / path).read_bytes()) for path in checked}
    original = source_checks();checks = [{'scenario': 'canonical_generated_portable_bytes', 'result': 'PASS', 'sha256': SHA}]
    server, url = serve()
    try:
        with tempfile.TemporaryDirectory(prefix='jpw-normative-portable-') as temp:
            portable = Path(temp) / 'standalone.html'
            portable.write_bytes((ROOT / 'dist/JP_Wealth_Risk_Terminal_V9.1_PORTABLE.html').read_bytes())
            with sync_playwright() as pw:
                browser = launch_browser(pw)
                for mode in modes:
                    address = (ROOT / 'index.html').as_uri() if mode == 'modular-file' else portable.as_uri() if mode == 'portable-file' else url
                    context, page, observed = boot(browser, address)
                    assert not observed['console'], context._nr_console_errors
                    if mode == 'offline':
                        page.evaluate('async()=>{await navigator.serviceWorker.ready}')
                        page.reload();page.wait_for_function('navigator.serviceWorker.controller!==null')
                        wait_bootstrap(page)
                        page.evaluate(SEED, {'version': 'V11.0+JPW-ANNEX-T03', 'accepted': True})
                        context.set_offline(True)
                    exercise(page, context, original, mode, screenshots)
                    if mode == 'offline':
                        # Test the actual controlled PWA cache independently of
                        # HTTP fault fixtures. Corruption stays inside this fresh
                        # synthetic context and is restored byte for byte.
                        before=page.evaluate(SNAPSHOT)
                        workers=page.evaluate("__normativeWorkers.filter(w=>w.name==='JPW Estatuto V11 local').length")
                        cached_sha=page.evaluate("""async path => {
                          JPWNormativeReader.leave();
                          const cache=await caches.open('jp-wealth-'+JP_WEALTH_BUILD_ID),url=new URL(path,document.baseURI).href;
                          const response=await cache.match(url);if(!response)throw new Error('Canonical document was not precached');
                          window.__nrCachedOriginal=new Uint8Array(await response.arrayBuffer());
                          const sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',__nrCachedOriginal)),v=>v.toString(16).padStart(2,'0')).join('');
                          const bad=__nrCachedOriginal.slice();bad[bad.length-1]^=1;
                          await cache.put(url,new Response(bad,{headers:{'Content-Type':'application/pdf'}}));
                          JPWNormativeReader.enter();return sha;
                        }""",PDF)
                        assert cached_sha==SHA
                        page.wait_for_function("nrIntegrity.dataset.state==='error' && nrStatus.textContent.includes('integridade')")
                        assert page.locator('#nrDownload').is_disabled() and not page.locator('#nrPageHost canvas').count()
                        assert page.evaluate("__normativeWorkers.filter(w=>w.name==='JPW Estatuto V11 local').length")==workers
                        page.evaluate("""async path => {
                          const cache=await caches.open('jp-wealth-'+JP_WEALTH_BUILD_ID);
                          await cache.put(new URL(path,document.baseURI).href,new Response(__nrCachedOriginal,{headers:{'Content-Type':'application/pdf'}}));
                          delete window.__nrCachedOriginal;
                        }""",PDF)
                        page.locator('#nrRetry').click();ready(page,1);unchanged(page,before)
                        checks.append({'scenario':'offline_cached_hash_blocked_before_worker_then_restored_retry','result':'PASS'})
                    assert_fixture_requests(context)
                    assert not observed['pageerror'], observed['pageerror']
                    assert not observed['console'], context._nr_console_errors
                    checks.append({'scenario': mode, 'result': 'PASS', 'renderedPages': [1, 2, 3, 86, 91, 110, 125], 'searchAll125PagesAccentCaseInsensitive': True, 'searchCopyDownload': True, 'protectedStateUnchanged': True, 'resourcesReleased': True})
                    print(mode + ': PASS', flush=True);context.close()
                # Merely consulting the document cannot record the pending
                # statute acceptance or otherwise complete onboarding.
                context, page, observed = boot(browser, url, accepted=False)
                before=page.evaluate(SNAPSHOT)
                assert before['onboarding']['consentAccepted'] is False
                navigate(page);ready(page, 1)
                page.locator('#nrSearch').fill('capital');page.locator('#nrFind').click()
                page.wait_for_function("nrSearchStatus.textContent.startsWith('Resultado ')");ready(page)
                with page.expect_download() as pending:page.locator('#nrDownload').click()
                assert digest(Path(pending.value.path()).read_bytes()) == SHA
                unchanged(page,before)
                assert page.evaluate('S.onboarding.consentAccepted') is False
                assert not observed['pageerror'] and not observed['console'], observed
                checks.append({'scenario':'pending_consent_open_search_download_preserved','result':'PASS'})
                context.close()
                # Genuine missing-document response is visible and blocks all
                # original actions until a successful retry. Its sole expected
                # browser console entry is attributed to this injected 404.
                # Block SW only for HTTP error fixtures so their corrupt/404
                # responses cannot race the actual SW precache and claim phase.
                # Nominal offline and corrupted-cache checks use the real SW.
                context, page, observed = boot(browser, url, service_workers='block')
                before=page.evaluate(SNAPSHOT)
                context.route('**/' + PDF, lambda route: route.fulfill(status=404, content_type='text/plain', body='Synthetic unavailable document'))
                navigate(page)
                page.wait_for_function("nrIntegrity.dataset.state==='error' && nrStatus.textContent.includes('não está disponível')")
                assert page.locator('#nrDownload').is_disabled() and page.locator('#nrOriginal').get_attribute('aria-disabled')=='true'
                assert not page.locator('#nrPageHost canvas').count()
                assert not page.evaluate("__normativeWorkers.some(w=>w.name==='JPW Estatuto V11 local')")
                assert len(context._nr_console_errors)==1 and PDF in context._nr_console_errors[0]['location']['url'] and '404' in context._nr_console_errors[0]['text'], context._nr_console_errors
                context.unroute('**/' + PDF);page.locator('#nrRetry').click();ready(page,1)
                unchanged(page,before)
                assert not observed['pageerror'] and len(observed['console'])==1,observed
                checks.append({'scenario':'missing_document_404_blocked_then_retry','result':'PASS','expectedInjected404Console':1})
                context.close()
                # Failure before worker creation, followed by real recovery.
                context, page, observed = boot(browser, url, service_workers='block')
                bad = original[:-1] + bytes([original[-1] ^ 1])
                context.route('**/' + PDF, lambda route: route.fulfill(status=200, content_type='application/pdf', body=bad))
                navigate(page)
                page.wait_for_function("nrIntegrity.dataset.state==='error' && nrStatus.textContent.includes('integridade')")
                assert not page.locator('#nrPageHost canvas').count()
                assert not page.evaluate("__normativeWorkers.some(w=>w.name==='JPW Estatuto V11 local')")
                context.unroute('**/' + PDF)
                page.locator('#nrRetry').click();ready(page, 1)
                checks.append({'scenario': 'wrong_hash_blocked_before_worker_then_retry', 'result': 'PASS'})
                page.evaluate("JPWNormativeReader.leave();window.__savedNormativeWorker=Worker;window.Worker=class{constructor(){throw new Error('Synthetic unavailable worker')}};JPWNormativeReader.enter()")
                page.wait_for_function("nrIntegrity.dataset.state==='verified' && nrStatus.textContent.includes('leitor local não pôde')")
                assert page.locator('#nrDownload').is_enabled() and page.locator('#nrOriginal').get_attribute('aria-disabled') == 'false'
                assert not page.locator('#nrPageHost canvas').count()
                with page.expect_download() as pending:page.locator('#nrDownload').click()
                assert digest(Path(pending.value.path()).read_bytes()) == SHA
                page.evaluate('() => {window.Worker=window.__savedNormativeWorker}')
                page.locator('#nrRetry').click();ready(page, 1)
                checks.append({'scenario': 'worker_unavailable_verified_original_then_retry', 'result': 'PASS'})
                page.evaluate("window.__nrGetContext=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(){return null}")
                page.locator('#nrPage').fill('2');page.locator('#nrPage').press('Enter')
                page.wait_for_function("nrStatus.dataset.state==='error' && nrStatus.textContent.includes('renderizar a página 2') && jpwNormativePage.getAttribute('aria-busy')==='false'")
                assert not page.locator('#nrPageHost canvas').count() and page.locator('#nrDownload').is_enabled()
                page.evaluate('() => {HTMLCanvasElement.prototype.getContext=window.__nrGetContext}')
                page.locator('#nrRetry').click();ready(page,2)
                checks.append({'scenario':'canvas_unavailable_page_error_then_retry','result':'PASS'})
                go(page,1)
                # Mobile in each theme, using the integrated application CSS.
                page.set_viewport_size({'width': 390, 'height': 844})
                for theme in ('dark', 'light'):
                    page.evaluate("theme=>{document.documentElement.dataset.theme=theme;document.body.dataset.theme=theme}", theme)
                    page.locator('#nrFit').click();ready(page, 1)
                    assert pixels(page)['ink'] > 20
                    layout = page.evaluate("({page:document.documentElement.scrollWidth,screen:innerWidth,panel:jpwNormativePage.getBoundingClientRect().width,viewport:nrViewport.clientWidth})")
                    assert layout['page'] <= layout['screen'] + 2, (theme, layout)
                    assert layout['panel'] > 200 and layout['viewport'] > 160, layout
                    if screenshots:page.locator('#jpwNormativePage').screenshot(path=str(screenshots / ('mobile-' + theme + '.png')))
                checks.append({'scenario': 'mobile_390_two_themes', 'result': 'PASS'})
                assert not observed['pageerror'] and not observed['console'], observed
                context.close();browser.close()
    finally:
        server.shutdown();server.server_close()
    assert source_hashes == {path: digest((ROOT / path).read_bytes()) for path in checked}, 'reader inputs changed; rerun focused test'
    report = {'result': 'PASS', 'scope':'normative reader', 'syntheticOnly': True, 'sourceHashes': source_hashes, 'checks': checks, 'limits': 'Chromium automation. Native original PDF display, Safari/iOS and screen-reader usability remain NOT_RUN; product SW update is a separate check.'}
    if output:output.write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n')
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
